### ISSUE TITLE
How can I use int4range in a Model?

### ISSUE THREAD

**Issue by martimarkov** [aejnsn/postgresify#13]

**Comment by aejnsn** [comment]
My apologies for the crazy late response. I'm assuming you mean to use an int4range in a migration? If that's the case, check this out: https://github.com/aejnsn/postgresify/blob/master/src/Database/Schema/Blueprint.php#L149

Something like this:
```php
Schema::create('planes', function (Blueprint $table) {
    $table->integerRange('seats');
});
```

Keep in mind, brackets are inclusive, parentheses are exclusive.
