### ISSUE TITLE
No version for minimum stability

### ISSUE THREAD

**Issue by cihantas** [aejnsn/postgresify#8]
Hey,

first of all thanks for the amazing effort. I get the following error when trying to require the package in composer.

```
[InvalidArgumentException]
Could not find package aejnsn/postgresify at any version for your minimum-s
tability (stable). Check the package spelling or your minimum-stability
```

Do I get this error because postgresify is still in development?

**Comment by aejnsn** [comment]
Hi @cihantas,

How are you requiring this in your composer.json? The dev-master should definitely be available. There is not versioned release as of yet.

**Comment by ha17** [comment]
I got this message, too, and had to edit composer.json to add: "aejnsn/postgresify": "@dev"
